# Generated by Django 5.0.11 on 2025-05-11 15:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensors', '0014_alter_spectralreading_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_type', models.CharField(choices=[('ANN', 'Artificial Neural Network'), ('RF', 'Random Forest'), ('SVM', 'Support Vector Machine')], max_length=3)),
                ('accuracy', models.FloatField(default=0.0)),
                ('precision', models.FloatField(default=0.0)),
                ('recall', models.FloatField(default=0.0)),
                ('f1_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parameters', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MLTestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('ann_prediction', models.CharField(blank=True, max_length=100, null=True)),
                ('rf_prediction', models.CharField(blank=True, max_length=100, null=True)),
                ('svm_prediction', models.CharField(blank=True, max_length=100, null=True)),
                ('ann_confidence', models.JSONField(default=dict)),
                ('rf_confidence', models.JSONField(default=dict)),
                ('svm_confidence', models.JSONField(default=dict)),
                ('test_name', models.CharField(default='Test ML', max_length=100)),
                ('spectral_reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.spectralreading')),
            ],
            options={
                'verbose_name': 'ML Test Data',
                'verbose_name_plural': 'ML Test Data',
                'ordering': ['-created_at'],
            },
        ),
    ]
