# Generated by Django 5.0.11 on 2025-02-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HoneyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('honey_type', models.CharField(choices=[('Hutan', 'Hutan'), ('Peternakan', 'Peternakan'), ('Lulut', 'Lulut')], max_length=50)),
                ('spectrum_readings', models.JSONField()),
            ],
        ),
    ]
