# Generated by Django 5.0.11 on 2025-02-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='honeydata',
            name='manual_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
