# Generated by Django 5.0.11 on 2025-02-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_honeydata_manual_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpectralReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device_id', models.CharField(max_length=50)),
                ('v410', models.FloatField()),
                ('v440', models.FloatField()),
                ('v470', models.FloatField()),
                ('v510', models.FloatField()),
                ('v550', models.FloatField()),
                ('v583', models.FloatField()),
                ('n680', models.FloatField()),
                ('n705', models.FloatField()),
                ('n730', models.FloatField()),
                ('n760', models.FloatField()),
                ('n810', models.FloatField()),
                ('n860', models.FloatField()),
                ('u350', models.FloatField()),
                ('u385', models.FloatField()),
                ('u420', models.FloatField()),
                ('u450', models.FloatField()),
                ('u475', models.FloatField()),
                ('u600', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='HoneyData',
        ),
    ]
