# Generated by Django 5.0.11 on 2025-02-08 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_spectralreading_delete_honeydata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spectralreading',
            old_name='device_id',
            new_name='name',
        ),
    ]
