# Generated by Django 5.0.11 on 2025-02-09 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_rename_device_id_spectralreading_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spectralreading',
            old_name='n680',
            new_name='nir_610',
        ),
        migrations.RenameField(
            model_name='spectralreading',
            old_name='n705',
            new_name='nir_680',
        ),
        migrations.RenameField(
            model_name='spectralreading',
            old_name='n730',
            new_name='nir_730',
        ),
        migrations.RenameField(
            model_name='spectralreading',
            old_name='n760',
            new_name='nir_760',
        ),
        migrations.RenameField(
            model_name='spectralreading',
            old_name='n810',
            new_name='nir_810',
        ),
        migrations.RenameField(
            model_name='spectralreading',
            old_name='n860',
            new_name='nir_860',
        ),
        migrations.RenameField(
            model_name='spectralreading',
            old_name='u350',
            new_name='uv_410',
        ),
        migrations.RenameField(
            model_name='spectralreading',
            old_name='u385',
            new_name='uv_435',
        ),
        migrations.RenameField(
            model_name='spectralreading',
            old_name='u420',
            new_name='uv_460',
        ),
        migrations.RenameField(
            model_name='spectralreading',
            old_name='u450',
            new_name='uv_485',
        ),
        migrations.RenameField(
            model_name='spectralreading',
            old_name='u475',
            new_name='uv_510',
        ),
        migrations.RenameField(
            model_name='spectralreading',
            old_name='u600',
            new_name='uv_535',
        ),
        migrations.RenameField(
            model_name='spectralreading',
            old_name='v410',
            new_name='vis_560',
        ),
        migrations.RenameField(
            model_name='spectralreading',
            old_name='v440',
            new_name='vis_585',
        ),
        migrations.RenameField(
            model_name='spectralreading',
            old_name='v470',
            new_name='vis_645',
        ),
        migrations.RenameField(
            model_name='spectralreading',
            old_name='v510',
            new_name='vis_705',
        ),
        migrations.RenameField(
            model_name='spectralreading',
            old_name='v550',
            new_name='vis_900',
        ),
        migrations.RenameField(
            model_name='spectralreading',
            old_name='v583',
            new_name='vis_940',
        ),
    ]
