# Generated by Django 5.0.11 on 2025-02-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0005_rename_n680_spectralreading_nir_610_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spectralreading',
            name='name',
            field=models.CharField(blank=True, default='Unknown', max_length=255),
        ),
    ]
