# Generated by Django 5.0.11 on 2025-02-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0007_alter_spectralreading_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spectralreading',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
