# Generated by Django 5.0.11 on 2025-02-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0008_alter_spectralreading_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spectralreading',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
