# Generated by Django 5.0.11 on 2025-02-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0009_alter_spectralreading_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spectralreading',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
