# Generated by Django 5.0.11 on 2025-03-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0011_spectralreading_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectralreading',
            name='kode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
