# Generated by Django 5.0.11 on 2025-03-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0012_spectralreading_kode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spectralreading',
            name='temperature',
            field=models.FloatField(default=25.0),
        ),
    ]
