# Generated by Django 5.0.11 on 2025-03-26 05:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0013_alter_spectralreading_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spectralreading',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
