version: '3'
services:
  web:
    build: madu-software .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
      - ./staticfiles:/app/staticfiles
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
