# Generated by Django 5.0.11 on 2025-04-23 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sensor_type', models.CharField(max_length=50)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ESP32Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My ESP32', max_length=100)),
                ('device_id', models.CharField(blank=True, max_length=50, null=True)),
                ('wifi_ssid', models.CharField(blank=True, max_length=100, null=True)),
                ('wifi_password', models.CharField(blank=True, max_length=100, null=True)),
                ('integration_time', models.IntegerField(default=100)),
                ('gain', models.FloatField(default=1.0)),
                ('led_brightness', models.IntegerField(default=50)),
                ('sampling_interval', models.IntegerField(default=1000)),
                ('is_connected', models.BooleanField(default=False)),
                ('last_connected', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esp32_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DynamicSensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('value', models.FloatField()),
                ('json_data', models.TextField(blank=True, null=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='dashboard.dynamicsensor')),
                ('esp32', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data', to='dashboard.esp32settings')),
            ],
        ),
    ]
