# Generated by Django 5.0.11 on 2025-02-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default-profile.png', upload_to='accounts'),
        ),
    ]
