# Generated by Django 5.0.11 on 2025-03-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_image_profile_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='google_avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
